### PR TITLE
Added a test for prefix in the kernelspec.

### LINKED ISSUE #6: WINDOWS: problem with kernel.json wrong path
Users reported problems with a fresh conda environment while running:

```cmd
> jupyter notebook --ip=127.0.0.1
```
The kernel died immediately with some Windows error message: [Error2] System cannot find file (*translated from german*).

This can be fixed by getting the kernelspec file via:

```cmd
> jupyter kernelspec list
```
and deleting the kernel.json at the displayed path.

I quickly checked the `conda-forge` `ipykernel` archives and the `default` one. The only difference: In the conda-forge there is another folder `share` which has the kernelspec json-file inside. 

But the path within the json file is wrong also after installation:

```json
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "C:\\conda\\envs\\_build\\python.exe", 
  "-m", 
  "ipykernel", 
  "-f", 
  "{connection_file}"
 ]
}
```
I'm not sure, how this should work, but this path should be changed to the correct location while installing `ipykernel`-package.

### PR DESCRIPTION
**Pull request by pelson**
Attempting to close #6.

### CODE REVIEW

**Comment by minrk** [comment]
Maybe it's the fact that it's JSON, so the path has `\\` for path separators instead of `\`, and it's not detecting that?

**Comment by pelson** [comment]
I'd agree. @msarahan - I think there is a conda-build bug here (around https://github.com/conda/conda-build/blob/master/conda_build/build.py#L122-L137?). Have you seen anything like this before?

In the meantime, maybe we should just replace the prefix manually in the json @minrk. Shouldn't be too hard to implement.

**Comment by minrk** [comment]
I'm not quite sure a manual patch will work, because both conda-build and conda-install need to detect the path. If conda-build doesn't detect it correctly, that suggests that if we patch it manually at build time, conda-install won't patch it correctly at install time. Should be easy enough to find out, though.

**Comment by msarahan** [comment]
I have not seen this before.  Is this something that needs to hold up the 1.20.3 release, or can it wait a bit?

Should conda-build be using a regex there instead of just find?  Would it suffice to double up backslashes with a string replace before finding (in addition to finding single backslashes?)

**Comment by minrk** [comment]
@msarahan in this case, I believe handling `\\` in addition to `\` would be sufficient.

**Comment by msarahan** [comment]
Like this? https://github.com/conda/conda-build/pull/962

**Comment by pelson** [comment]
> Like this? conda/conda-build#962

Looks plausible. If you are happy to give it a shot then I'll hold fire on this PR. If not, I will try to get that conda-build PR running on AppVeyor so that we can try it out and confirm.

**Comment by msarahan** [comment]
@pelson please let me know asap.  If you can tell me in the next 30 min or so, I'll merge it into 1.20.3.  Otherwise, it will have to wait for the next release.

I added a test to that PR - please tell if that is a good test of this functionality or not.

**Comment by jakirkham** [comment]
I'm not sure when @pelson leaves, but I think it is soon. If I can help facilitate something here, please let me know, @msarahan.

**Comment by pelson** [comment]
@jakirkham - away in ~20hrs

**Comment by pelson** [comment]
Sorry @msarahan - think we had a mis-understanding. If you were going to merge that PR, I would have just waited for the release. If you wanted conda-build testing of that PR, I would have had to jump through a few hoops as I have no Windows dev box to hand.
Given that PR didn't make the cut, we may need to find an alternative fix in this PR.

**Comment by jakirkham** [comment]
> @jakirkham - away in ~20hrs

Ah, sorry, knew it was sometime in the middle end of this week, but was unclear on exactly when.

**Comment by jakirkham** [comment]
Well that PR did land in 1.21.0 IIRC. Maybe it is worth resurrecting this.

**Comment by jakirkham** [comment]
Should add that I re-rendered `master`. So we may need to merge/rebase with it if the installed versions are screwy.

**Pull request closed without merging**
