### PR TITLE
ipykernel 6.12.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by minrk — APPROVED** [review]

**Comment by bollwyvl** [comment]
> [minrk](https://github.com/minrk) added the automerge label [now](https://github.com/conda-forge/ipykernel-feedstock/pull/124#event-6362521066)

i dunno, i have fear :laughing:

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by minrk** [comment]
> i dunno, i have fear 

Bot's smart - it doesn't merge unless it's all green, and won't merge if you push new commits. It's just a handy way for me to say "merge if it's all green" which is what I was going to do anyway, so I don't have to wait and stare at the little orange circles.

**Comment by blink1073** [comment]
Might want to hold off before adding new test deps: https://github.com/ipython/ipykernel/pull/904

**Comment by minrk** [comment]
I _really_ want to find a fix to allow this package to be noarch. Feels so silly to need all those platform builds just for the path in kernel.json.

**Comment by bollwyvl** [comment]
> Bot's smart

oh, i know, but i sometimes watch these monster builds a little more closely... nothing like a ClobberWarning to ruin your day... but...

> hold off before adding new test deps:

it passes, are we sad? seems to work.

> allow this package to be noarch. 

welp, we actually can now, as we can do multi-platform noarch builds:

https://conda-forge.org/docs/maintainer/conda_forge_yml.html?highlight=noarch_platforms#noarch-platforms

so basically we'd have an `ipykernel` that only worked on unix and one that worked on windows. i'll issue up...

**Review by bollwyvl — COMMENTED** [review]
:heavy_check_mark: can't approve my own, but LGTM, no further changes planned

**Comment by minrk** [comment]
Everything passed!

**Pull request merged**
