### PR TITLE
release 4.4

### PR DESCRIPTION
**Pull request by minrk**
tornado is needed in build for the kernelspec install invocation

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems to be failing on CircleCI and AppVeyor due to issue ( https://github.com/conda-forge/conda-feedstock/issues/1 ). Interestingly the Travis CI doesn't fail, but it is like because `conda-build` is [still pinned]( https://github.com/conda-forge/ipykernel-feedstock/blob/575556885c2b7292fbd2c4f2906b27953558881e/.travis.yml#L34 ) on this feedstock as seen in the [log]( https://travis-ci.org/conda-forge/ipykernel-feedstock/jobs/150660840#L345-L346 ).

**Comment by jakirkham** [comment]
Broken packages have been pulled. So that shouldn't be an issue.

To fix the other issue this feedstock needs to be re-rendered. Please see PR ( https://github.com/conda-forge/ipykernel-feedstock/pull/9 ), which will do exactly that.

**Comment by jakirkham** [comment]
Merged the aforementioned PR and restarted the CIs for this PR. May need to merge with `master` if we are still seeing failures.

**Comment by jakirkham** [comment]
Yeah, this is still failing on Travis CI. However, that seems to be because it is using the `.travis.yml` file from your branch and not the one from `master`. Merging or rebasing on `master` should fix the issue.

**Comment by minrk** [comment]
Found a bug in 4.4 that we are working on, so I might hold this for 4.4.1, which we should have shortly.

**Pull request merged**
