### PR TITLE
Release 5.0.0.

### PR DESCRIPTION
**Pull request by blink1073**
Unlike 4.10.0 that was just released this is Python 3 only (drop 3.4
support and bump the compatibility with IPython to IPython 5+ required).

It also have all the machinery to have async/await top level.

I believe the modification I've done to the recipe are sufficient, but
I'd appreciate if one can be extra careful

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by Carreau** [comment]
Thanks @blink1073 !

**Comment by hmaarrfk** [comment]
should this be a `noarch` package? It seems to be so on PyPi

**Comment by Carreau** [comment]
> should this be a `noarch` package? It seems to be so on PyPi

Well, now that it doped 2.7, likely yes. I'm debugging another issue right now do you want to send a PR against my branch ?

**Comment by hmaarrfk** [comment]
I see, it couldn't be noarch because of python3/2 things? I thought noarch also worked on that.

**Comment by Carreau** [comment]
> I see, it couldn't be noarch because of python3/2 things? I thought noarch also worked on that.

Yes, _if_ it's a library. We do install `ipykernel2` on Python 2 and `ipykernel3` on Python 3 (or something like that)

THat is why the previous version (4.10) had 2 weels https://pypi.org/project/ipykernel/4.10.0/#files

**Comment by hmaarrfk** [comment]
Got it, so it can't be noarch + python version restrictions.

This is mostly because appveyor will never actually build this package and spyder is broken currently.

Trying to get people to install spyder on windows is really demoralizing for them

**Comment by hmaarrfk** [comment]
See https://github.com/Carreau/ipykernel-feedstock/pull/1 if you haven't already

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
IIRC noarch and Py3-only are incompatible.

**Comment by hmaarrfk** [comment]
@blink1073 you can't do it with the "skip" directive, but you can do it with the version restrictions.

https://github.com/conda-forge/ipykernel-feedstock/pull/32/files#diff-e178b687b10a71a3348107ae3154e44cR21

**Comment by blink1073** [comment]
good to know, thanks @hmaarrfk!

**Comment by blink1073** [comment]
Let's wait for #33, then I'll rebase this.

**Comment by blink1073** [comment]
Couldn't force push the rebase, closing in favor of #34.

**Pull request closed without merging**
