### PR TITLE
Release 4.10.0

### PR DESCRIPTION
**Pull request by Carreau**
Minor release, almost no changes beside some compatibility with Spyder
on windows and IPython 7+ (coming soon)

Httpsify link, adds me as maintainer.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Carreau** [comment]
Once this is merged, the following can be submitted to release 5.0.0: 
https://github.com/Carreau/ipykernel-feedstock/pull/new/5.0.0

**Comment by blink1073** [comment]
Ha, auto bot beat you to the punch. 😉

**Comment by blink1073** [comment]
I'm not admin on this either, I think only the conda-forge core folks are.

**Comment by Carreau** [comment]
But you can close the other pull-request you are listed as a maintainer, I think that should cancel Appveyor.

**Comment by jakirkham** [comment]
Both of you should already have permissions. 😉 Just need to login to AppVeyor.

**Comment by blink1073** [comment]
Ah, thanks for the heads up @jakirkham!

**Comment by Carreau** [comment]
Many thanks.

**Pull request merged**
