### PR TITLE
back out pinning pyzmq

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Pin `pyzmq >=22.0.1` instead of `<21` since that fixes the problem. Overrides #74

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
why can't aarch64 find pyzmq>=20.0.1? The pyzmq-feedstock seems to have built it ...

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Yeah, i'm stumped. Maybe we wait for https://github.com/conda-forge/pyzmq-feedstock/pull/71 ?

**Comment by bollwyvl** [comment]
Maybe we roll this into #76?

**Comment by bollwyvl** [comment]
i guess i never understood the actual issue...

**Comment by bollwyvl** [comment]
@conda-forge/ipykernel should we ditch travis?

**Comment by bollwyvl** [comment]
Over on https://github.com/conda-forge/aiohttp-feedstock/pull/53#issuecomment-782359273 i'm seeing the same ppc error, even on azure, so i don't think the whole blame can be placed on travis.

Looking at the actual pin: this seems pretty heavy. I've removed the pin altogether, as it _should_ bring in the `22.x` line for everything here. Even if it "fixes" a problem, I feel like a downstream pinning an upstream's deps seldom creates useful situations down the road.

If anything, we could put the pin back in as `!=21`, which would have much less of a long-term impact.

**Comment by bollwyvl** [comment]
Cool, ppc even ran. I'll put the `!=21` back in, and then merge if it comes up green.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by bollwyvl** [comment]
one of the aarch builds flaked, re-kicked...

**Comment by bollwyvl** [comment]
Worked the second time:

```
linux-64/ipykernel-5.4.3-py36he2ddec3_1.tar.bz2
linux-64/ipykernel-5.4.3-py36he448a4c_1.tar.bz2
linux-64/ipykernel-5.4.3-py37h2b89940_1.tar.bz2
linux-64/ipykernel-5.4.3-py37h888b3d9_1.tar.bz2
linux-64/ipykernel-5.4.3-py38h81c977d_1.tar.bz2
linux-64/ipykernel-5.4.3-py39hef51801_1.tar.bz2
linux-aarch64/ipykernel-5.4.3-py36h0e46ebc_1.tar.bz2
linux-aarch64/ipykernel-5.4.3-py36h5407763_1.tar.bz2
linux-aarch64/ipykernel-5.4.3-py37h9e1f083_1.tar.bz2
linux-aarch64/ipykernel-5.4.3-py37hc16ab0a_1.tar.bz2 
linux-aarch64/ipykernel-5.4.3-py38hd825144_1.tar.bz2
linux-aarch64/ipykernel-5.4.3-py39hef158d4_1.tar.bz2
linux-ppc64le/ipykernel-5.4.3-py36h005af8b_1.tar.bz2
linux-ppc64le/ipykernel-5.4.3-py36h624fdba_1.tar.bz2
linux-ppc64le/ipykernel-5.4.3-py37h7b46356_1.tar.bz2
linux-ppc64le/ipykernel-5.4.3-py37hfeca116_1.tar.bz2
linux-ppc64le/ipykernel-5.4.3-py38h3c958fc_1.tar.bz2
linux-ppc64le/ipykernel-5.4.3-py39h0de2273_1.tar.bz2
osx-64/ipykernel-5.4.3-py36h9cf137f_1.tar.bz2
osx-64/ipykernel-5.4.3-py36hdc2d08f_1.tar.bz2
osx-64/ipykernel-5.4.3-py37h5b6bc8d_1.tar.bz2
osx-64/ipykernel-5.4.3-py37he01cfaa_1.tar.bz2
osx-64/ipykernel-5.4.3-py38h9bb44b7_1.tar.bz2
osx-64/ipykernel-5.4.3-py39h71a6800_1.tar.bz2
osx-arm64/ipykernel-5.4.3-py38h2cb4d76_1.tar.bz2
osx-arm64/ipykernel-5.4.3-py39h32adebf_1.tar.bz2
win-64/ipykernel-5.4.3-py36h7b2dad6_1.tar.bz2
win-64/ipykernel-5.4.3-py37heaed05f_1.tar.bz2
win-64/ipykernel-5.4.3-py38hc5df569_1.tar.bz2
win-64/ipykernel-5.4.3-py39h832f523_1.tar.bz2
```

**Pull request merged**
