### PR TITLE
Release 4.7.0

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin please rerender

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender.

**Comment by blink1073** [comment]
Ready for merge!

**Comment by blink1073** [comment]
Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
Thank you for the PR (and for taking the helm as a maintainer :wink:)

**Pull request merged**
