### PR TITLE
ipykernel 5.4.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- trying with all of the test skips taken out, upstreamed as of https://github.com/ipython/ipykernel/pull/564#

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Looks good:
```
linux-64/ipykernel-5.4.0-py36he2ddec3_0.tar.bz2
linux-64/ipykernel-5.4.0-py36he448a4c_0.tar.bz2
linux-64/ipykernel-5.4.0-py37h888b3d9_0.tar.bz2
linux-64/ipykernel-5.4.0-py38h81c977d_0.tar.bz2
linux-64/ipykernel-5.4.0-py39hef51801_0.tar.bz2
linux-aarch64/ipykernel-5.4.0-py36h0e46ebc_0.tar.bz2
linux-aarch64/ipykernel-5.4.0-py36h5407763_0.tar.bz2
linux-aarch64/ipykernel-5.4.0-py37hc16ab0a_0.tar.bz2
linux-aarch64/ipykernel-5.4.0-py38hd825144_0.tar.bz2
linux-aarch64/ipykernel-5.4.0-py39hef158d4_0.tar.bz2
linux-ppc64le/ipykernel-5.4.0-py36h005af8b_0.tar.bz2
linux-ppc64le/ipykernel-5.4.0-py36h624fdba_0.tar.bz2
linux-ppc64le/ipykernel-5.4.0-py37h7b46356_0.tar.bz2
linux-ppc64le/ipykernel-5.4.0-py38h3c958fc_0.tar.bz2
linux-ppc64le/ipykernel-5.4.0-py39h0de2273_0.tar.bz2
osx-64/ipykernel-5.4.0-py36h9cf137f_0.tar.bz2
osx-64/ipykernel-5.4.0-py36hdc2d08f_0.tar.bz2
osx-64/ipykernel-5.4.0-py37he01cfaa_0.tar.bz2
osx-64/ipykernel-5.4.0-py38h9bb44b7_0.tar.bz2
osx-64/ipykernel-5.4.0-py39h71a6800_0.tar.bz2
osx-arm64/ipykernel-5.4.0-py38h2cb4d76_0.tar.bz2
osx-arm64/ipykernel-5.4.0-py39h32adebf_0.tar.bz2
win-64/ipykernel-5.4.0-py36h7b7c402_0.tar.bz2
win-64/ipykernel-5.4.0-py37h7b7c402_0.tar.bz2
win-64/ipykernel-5.4.0-py38h7b7c402_0.tar.bz2
win-64/ipykernel-5.4.0-py39he1a07ef_0.tar.bz2 
```

**Comment by blink1073** [comment]
Thanks @bollwyvl!

**Comment by bollwyvl** [comment]
Yeah, well, it didn't fix our downstream issues fully... But thanks
everyone for turning it around quick anyway, no doubt it was causing folks
issues.

**Pull request merged**
